---
title: "final test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## T分配
T分配:Z為標準常態分配，$X^2_\gamma$為自由度$\gamma$的卡方分配$$T=\frac{Z}{\sqrt{X^2_r /r}},df=X^2_\gamma$$
T分布函數:
$$公式:f(t)=\frac{\Gamma(\gamma+1)/2}{\Gamma(\gamma/2)\sqrt\pi\gamma}(1+\frac{t^2}{\gamma})^{-(\gamma+1)/2},-\infty<t<\infty$$
for $\sigma$ known:
$$\bar{x} \pm z_{\alpha/2}\frac{\sigma}{\sqrt{n}}$$
for $\sigma$ unknown:
$$\bar{x} \pm t_{\alpha/2}\frac{s}{\sqrt{n}},s=\sqrt{\frac{\Sigma{(x_i -\bar{x})^2}}{n-1}}$$

```{r}
one=c(300,280,344,385,372,360,288,321,376,290,301,283)
two=c(274,220,308,336,198,300,315,258,318,310,332,263)
a=length(one);b=length(two)
one_mean=mean(one);two_mean=mean(two);one_var=var(one);two_var=var(two)
aa=one_var/a;bb=two_var/b
t=((one_mean-two_mean)-0)/((one_var/a)+(two_var/b))^(1/2)
df=((aa+bb)^2)/((aa^2/(a-1))+(bb^2/(b-1)))
curve(dt(x,df=df),-5,5,ylab = "p(x)")
```

不顯示code


```{r,echo=FALSE}
one=c(300,280,344,385,372,360,288,321,376,290,301,283)
two=c(274,220,308,336,198,300,315,258,318,310,332,263)
a=length(one);b=length(two)
one_mean=mean(one);two_mean=mean(two);one_var=var(one);two_var=var(two)
aa=one_var/a;bb=two_var/b
t=((one_mean-two_mean)-0)/((one_var/a)+(two_var/b))^(1/2)
df=((aa+bb)^2)/((aa^2/(a-1))+(bb^2/(b-1)))
curve(dt(x,df=df),-5,5,ylab = "p(x)")
```


## Rmarkdown
* unordered list
* item2
  * sub-item
    
1. ordered list
2. item2
    * sub-time
    

Table Header  |Second Header 
--------------|--------------
Table Cell    |Cell2
Cell3         |Cell4  

$$\left[
    \begin{array}{cc}
      A & B \\
      C & D \\
    \end{array}
  \right]$$

$\left[
    \begin{array}{cc}
      A & B \\
      C & D \\
    \end{array}
  \right]$

two times three equal `r 2*3`

$X$ is a random variable with pmf as follows:

$x_j$| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 
-----|---|---|---|---|---|---|---|---|---|---
$p_j$|0.11|0.12|0.09|0.08|0.12|0.10|0.09|0.09|0.1|0.1

$$Table3:Randomvariable  X  with its probability$$
```{r,echo=FALSE}
x<-c(1,2,3,4,5,6,7,8,9,10)
p<-c(0.11,0.12,0.09,0.08,0.12,0.10,0.09,0.09,0.1,0.1)
plot((1:10),p,type = "p",pch=1,col="red",main="pmf",ylab="p(x)",xlab="x",bty="L",xlim=c(1,10))
points((1:10),rep(0.1,10),pch=4,col="blue")
segments((1:10),p,(1:10),rep(0,10),col="red")
legend("topright",c("pmf of X","pmf of Y"),col=c("red","blue"),pch=c(1,4))
```